"""more space

Revision ID: 765c5681aa0f
Revises: efa8e8a6a0f4
Create Date: 2022-09-27 21:41:31.523093

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '765c5681aa0f'
down_revision = 'efa8e8a6a0f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'team_accepted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
