"""team accept

Revision ID: 7851390f7694
Revises: d5ab3378491f
Create Date: 2022-09-24 22:55:10.597386

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7851390f7694'
down_revision = 'd5ab3378491f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'team_accepted')
    # ### end Alembic commands ###
