"""init

Revision ID: d1c23380e268
Revises: 
Create Date: 2022-09-24 18:18:06.898443

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_utils.types.choice
import sqlalchemy_utils.types.email
import sqlalchemy_utils.types.url

# revision identifiers, used by Alembic.
revision = 'd1c23380e268'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.Numeric(), nullable=False),
    sa.Column('picture', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('college', sa.String(length=30), nullable=True),
    sa.Column('course', sa.String(length=30), nullable=True),
    sa.Column('semester', sqlalchemy_utils.types.choice.ChoiceType(choices=(('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3'), ('s4', 'S4'), ('s5', 'S5'), ('s6', 'S6'), ('s7', 'S7'), ('s8', 'S8'), ('s9', 'S9'), ('s10', 'S10'))), nullable=True),
    sa.Column('tshirt', sqlalchemy_utils.types.choice.ChoiceType(choices=(('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'))), nullable=True),
    sa.Column('linkedin', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('github', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('first_hackathon', sa.Boolean(), nullable=True),
    sa.Column('experience', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
