"""team delete

Revision ID: efa8e8a6a0f4
Revises: 7851390f7694
Create Date: 2022-09-24 23:53:29.104865

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'efa8e8a6a0f4'
down_revision = '7851390f7694'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_team_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_team_id_fkey', 'user', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###
